version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    image: django-app
    ports:
      - "8000:8000"
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
