# Generated by Django 4.2 on 2025-01-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_created_at_post_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_add_post', 'Can add post')]},
        ),
    ]
